<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountryTableSeeder extends Seeder{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        $countries = array(
    		array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'isdcode' => 93,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 2,'code' => 'AL' ,'name' => "Albania",'isdcode' => 355,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 3,'code' => 'DZ' ,'name' => "Algeria",'isdcode' => 213,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 4,'code' => 'AS' ,'name' => "American Samoa",'isdcode' => 1684,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 5,'code' => 'AD' ,'name' => "Andorra",'isdcode' => 376,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 6,'code' => 'AO' ,'name' => "Angola",'isdcode' => 244,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 7,'code' => 'AI' ,'name' => "Anguilla",'isdcode' => 1264,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'isdcode' => 672,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'isdcode' => 1268,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 10,'code' => 'AR','name' => "Argentina",'isdcode' => 54,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 11,'code' => 'AM','name' => "Armenia",'isdcode' => 374,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 12,'code' => 'AW','name' => "Aruba",'isdcode' => 297,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 13,'code' => 'AU','name' => "Australia",'isdcode' => 61,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 14,'code' => 'AT','name' => "Austria",'isdcode' => 43,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 15,'code' => 'AZ','name' => "Azerbaijan",'isdcode' => 994,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 16,'code' => 'BS','name' => "Bahamas The",'isdcode' => 1242,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 17,'code' => 'BH','name' => "Bahrain",'isdcode' => 973,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 18,'code' => 'BD','name' => "Bangladesh",'isdcode' => 880,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 19,'code' => 'BB','name' => "Barbados",'isdcode' => 1246,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 20,'code' => 'BY','name' => "Belarus",'isdcode' => 375,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 21,'code' => 'BE','name' => "Belgium",'isdcode' => 32,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 22,'code' => 'BZ','name' => "Belize",'isdcode' => 501,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 23,'code' => 'BJ','name' => "Benin",'isdcode' => 229,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 24,'code' => 'BM','name' => "Bermuda",'isdcode' => 1441,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 25,'code' => 'BT','name' => "Bhutan",'isdcode' => 975,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 26,'code' => 'BO','name' => "Bolivia",'isdcode' => 591,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'isdcode' => 387,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 28,'code' => 'BW','name' => "Botswana",'isdcode' => 267,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 29,'code' => 'BV','name' => "Bouvet Island",'isdcode' => 47,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 30,'code' => 'BR','name' => "Brazil",'isdcode' => 55,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'isdcode' => 246,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 32,'code' => 'BN','name' => "Brunei",'isdcode' => 673,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 33,'code' => 'BG','name' => "Bulgaria",'isdcode' => 359,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 34,'code' => 'BF','name' => "Burkina Faso",'isdcode' => 226,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 35,'code' => 'BI','name' => "Burundi",'isdcode' => 257,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 36,'code' => 'KH','name' => "Cambodia",'isdcode' => 855,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 37,'code' => 'CM','name' => "Cameroon",'isdcode' => 237,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 38,'code' => 'CA','name' => "Canada",'isdcode' => 1,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 39,'code' => 'CV','name' => "Cape Verde",'isdcode' => 238,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 40,'code' => 'KY','name' => "Cayman Islands",'isdcode' => 1345,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 41,'code' => 'CF','name' => "Central African Republic",'isdcode' => 236,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 42,'code' => 'TD','name' => "Chad",'isdcode' => 235,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 43,'code' => 'CL','name' => "Chile",'isdcode' => 56,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 44,'code' => 'CN','name' => "China",'isdcode' => 86,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 45,'code' => 'CX','name' => "Christmas Island",'isdcode' => 61,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'isdcode' => 61891,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 47,'code' => 'CO','name' => "Colombia",'isdcode' => 57,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 48,'code' => 'KM','name' => "Comoros",'isdcode' => 269,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 49,'code' => 'CG','name' => "Congo",'isdcode' => 242,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'isdcode' => 242,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 51,'code' => 'CK','name' => "Cook Islands",'isdcode' => 682,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 52,'code' => 'CR','name' => "Costa Rica",'isdcode' => 506,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'isdcode' => 225,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'isdcode' => 385,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 55,'code' => 'CU','name' => "Cuba",'isdcode' => 53,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 56,'code' => 'CY','name' => "Cyprus",'isdcode' => 357,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 57,'code' => 'CZ','name' => "Czech Republic",'isdcode' => 420,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 58,'code' => 'DK','name' => "Denmark",'isdcode' => 45,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 59,'code' => 'DJ','name' => "Djibouti",'isdcode' => 253,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 60,'code' => 'DM','name' => "Dominica",'isdcode' => 1767,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 61,'code' => 'DO','name' => "Dominican Republic",'isdcode' => 1809,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 62,'code' => 'TP','name' => "East Timor",'isdcode' => 670,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 63,'code' => 'EC','name' => "Ecuador",'isdcode' => 593,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 64,'code' => 'EG','name' => "Egypt",'isdcode' => 20,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 65,'code' => 'SV','name' => "El Salvador",'isdcode' => 503,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'isdcode' => 240,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 67,'code' => 'ER','name' => "Eritrea",'isdcode' => 291,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 68,'code' => 'EE','name' => "Estonia",'isdcode' => 372,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 69,'code' => 'ET','name' => "Ethiopia",'isdcode' => 251,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 70,'code' => 'XA','name' => "External Territories of Australia",'isdcode' => 61,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 71,'code' => 'FK','name' => "Falkland Islands",'isdcode' => 500,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 72,'code' => 'FO','name' => "Faroe Islands",'isdcode' => 298,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 73,'code' => 'FJ','name' => "Fiji Islands",'isdcode' => 679,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 74,'code' => 'FI','name' => "Finland",'isdcode' => 358,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 75,'code' => 'FR','name' => "France",'isdcode' => 33,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 76,'code' => 'GF','name' => "French Guiana",'isdcode' => 594,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 77,'code' => 'PF','name' => "French Polynesia",'isdcode' => 689,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 78,'code' => 'TF','name' => "French Southern Territories",'isdcode' => NULL,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 79,'code' => 'GA','name' => "Gabon",'isdcode' => 241,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 80,'code' => 'GM','name' => "Gambia The",'isdcode' => 220,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 81,'code' => 'GE','name' => "Georgia",'isdcode' => 995,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 82,'code' => 'DE','name' => "Germany",'isdcode' => 49,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 83,'code' => 'GH','name' => "Ghana",'isdcode' => 233,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 84,'code' => 'GI','name' => "Gibraltar",'isdcode' => 350,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 85,'code' => 'GR','name' => "Greece",'isdcode' => 30,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 86,'code' => 'GL','name' => "Greenland",'isdcode' => 299,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 87,'code' => 'GD','name' => "Grenada",'isdcode' => 1473,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 88,'code' => 'GP','name' => "Guadeloupe",'isdcode' => 590,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 89,'code' => 'GU','name' => "Guam",'isdcode' => 1671,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 90,'code' => 'GT','name' => "Guatemala",'isdcode' => 502,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'isdcode' => 44,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 92,'code' => 'GN','name' => "Guinea",'isdcode' => 224,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'isdcode' => 245,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 94,'code' => 'GY','name' => "Guyana",'isdcode' => 592,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 95,'code' => 'HT','name' => "Haiti",'isdcode' => 509,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'isdcode' => 011,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 97,'code' => 'HN','name' => "Honduras",'isdcode' => 504,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'isdcode' => 852,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 99,'code' => 'HU','name' => "Hungary",'isdcode' => 36,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 100,'code' => 'IS','name' => "Iceland",'isdcode' => 354,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 101,'code' => 'IN','name' => "India",'isdcode' => 91,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 102,'code' => 'ID','name' => "Indonesia",'isdcode' => 62,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 103,'code' => 'IR','name' => "Iran",'isdcode' => 98,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 104,'code' => 'IQ','name' => "Iraq",'isdcode' => 964,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 105,'code' => 'IE','name' => "Ireland",'isdcode' => 353,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 106,'code' => 'IL','name' => "Israel",'isdcode' => 972,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 107,'code' => 'IT','name' => "Italy",'isdcode' => 39,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 108,'code' => 'JM','name' => "Jamaica",'isdcode' => 1876,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 109,'code' => 'JP','name' => "Japan",'isdcode' => 81,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 110,'code' => 'XJ','name' => "Jersey",'isdcode' => 44,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 111,'code' => 'JO','name' => "Jordan",'isdcode' => 962,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 112,'code' => 'KZ','name' => "Kazakhstan",'isdcode' => 7,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 113,'code' => 'KE','name' => "Kenya",'isdcode' => 254,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 114,'code' => 'KI','name' => "Kiribati",'isdcode' => 686,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 115,'code' => 'KP','name' => "Korea North",'isdcode' => 850,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 116,'code' => 'KR','name' => "Korea South",'isdcode' => 82,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 117,'code' => 'KW','name' => "Kuwait",'isdcode' => 965,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'isdcode' => 996,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 119,'code' => 'LA','name' => "Laos",'isdcode' => 856,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 120,'code' => 'LV','name' => "Latvia",'isdcode' => 371,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 121,'code' => 'LB','name' => "Lebanon",'isdcode' => 961,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 122,'code' => 'LS','name' => "Lesotho",'isdcode' => 266,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 123,'code' => 'LR','name' => "Liberia",'isdcode' => 231,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 124,'code' => 'LY','name' => "Libya",'isdcode' => 218,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 125,'code' => 'LI','name' => "Liechtenstein",'isdcode' => 423,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 126,'code' => 'LT','name' => "Lithuania",'isdcode' => 370,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 127,'code' => 'LU','name' => "Luxembourg",'isdcode' => 352,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'isdcode' => 853,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 129,'code' => 'MK','name' => "Macedonia",'isdcode' => 389,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 130,'code' => 'MG','name' => "Madagascar",'isdcode' => 261,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 131,'code' => 'MW','name' => "Malawi",'isdcode' => 265,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 132,'code' => 'MY','name' => "Malaysia",'isdcode' => 60,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 133,'code' => 'MV','name' => "Maldives",'isdcode' => 960,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 134,'code' => 'ML','name' => "Mali",'isdcode' => 223,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 135,'code' => 'MT','name' => "Malta",'isdcode' => 356,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 136,'code' => 'XM','name' => "Man (Isle of)",'isdcode' => 44,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 137,'code' => 'MH','name' => "Marshall Islands",'isdcode' => 692,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 138,'code' => 'MQ','name' => "Martinique",'isdcode' => 596,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 139,'code' => 'MR','name' => "Mauritania",'isdcode' => 222,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 140,'code' => 'MU','name' => "Mauritius",'isdcode' => 230,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 141,'code' => 'YT','name' => "Mayotte",'isdcode' => 262,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 142,'code' => 'MX','name' => "Mexico",'isdcode' => 52,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 143,'code' => 'FM','name' => "Micronesia",'isdcode' => 691,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 144,'code' => 'MD','name' => "Moldova",'isdcode' => 373,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 145,'code' => 'MC','name' => "Monaco",'isdcode' => 377,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 146,'code' => 'MN','name' => "Mongolia",'isdcode' => 976,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 147,'code' => 'MS','name' => "Montserrat",'isdcode' => 1664,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 148,'code' => 'MA','name' => "Morocco",'isdcode' => 212,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 149,'code' => 'MZ','name' => "Mozambique",'isdcode' => 258,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 150,'code' => 'MM','name' => "Myanmar",'isdcode' => 95,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 151,'code' => 'NA','name' => "Namibia",'isdcode' => 264,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 152,'code' => 'NR','name' => "Nauru",'isdcode' => 674,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 153,'code' => 'NP','name' => "Nepal",'isdcode' => 977,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'isdcode' => 599,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 155,'code' => 'NL','name' => "Netherlands The",'isdcode' => 31,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 156,'code' => 'NC','name' => "New Caledonia",'isdcode' => 687,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 157,'code' => 'NZ','name' => "New Zealand",'isdcode' => 64,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 158,'code' => 'NI','name' => "Nicaragua",'isdcode' => 505,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 159,'code' => 'NE','name' => "Niger",'isdcode' => 227,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 160,'code' => 'NG','name' => "Nigeria",'isdcode' => 234,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 161,'code' => 'NU','name' => "Niue",'isdcode' => 683,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 162,'code' => 'NF','name' => "Norfolk Island",'isdcode' => 672,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'isdcode' => 1670,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 164,'code' => 'NO','name' => "Norway",'isdcode' => 47,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 165,'code' => 'OM','name' => "Oman",'isdcode' => 968,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 166,'code' => 'PK','name' => "Pakistan",'isdcode' => 92,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 167,'code' => 'PW','name' => "Palau",'isdcode' => 680,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'isdcode' => 970,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 169,'code' => 'PA','name' => "Panama",'isdcode' => 507,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 170,'code' => 'PG','name' => "Papua new Guinea",'isdcode' => 675,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 171,'code' => 'PY','name' => "Paraguay",'isdcode' => 595,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 172,'code' => 'PE','name' => "Peru",'isdcode' => 51,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 173,'code' => 'PH','name' => "Philippines",'isdcode' => 63,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 174,'code' => 'PN','name' => "Pitcairn Island",'isdcode' => 64,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 175,'code' => 'PL','name' => "Poland",'isdcode' => 48,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 176,'code' => 'PT','name' => "Portugal",'isdcode' => 351,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 177,'code' => 'PR','name' => "Puerto Rico",'isdcode' => 1787,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 178,'code' => 'QA','name' => "Qatar",'isdcode' => 974,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 179,'code' => 'RE','name' => "Reunion",'isdcode' => 262,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 180,'code' => 'RO','name' => "Romania",'isdcode' => 40,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 181,'code' => 'RU','name' => "Russia",'isdcode' => 70,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 182,'code' => 'RW','name' => "Rwanda",'isdcode' => 250,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 183,'code' => 'SH','name' => "Saint Helena",'isdcode' => 290,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'isdcode' => 1869,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 185,'code' => 'LC','name' => "Saint Lucia",'isdcode' => 1758,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'isdcode' => 508,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'isdcode' => 1784,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 188,'code' => 'WS','name' => "Samoa",'isdcode' => 684,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 189,'code' => 'SM','name' => "San Marino",'isdcode' => 378,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'isdcode' => 239,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 191,'code' => 'SA','name' => "Saudi Arabia",'isdcode' => 966,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 192,'code' => 'SN','name' => "Senegal",'isdcode' => 221,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 193,'code' => 'RS','name' => "Serbia",'isdcode' => 381,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 194,'code' => 'SC','name' => "Seychelles",'isdcode' => 248,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 195,'code' => 'SL','name' => "Sierra Leone",'isdcode' => 232,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 196,'code' => 'SG','name' => "Singapore",'isdcode' => 65,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 197,'code' => 'SK','name' => "Slovakia",'isdcode' => 421,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 198,'code' => 'SI','name' => "Slovenia",'isdcode' => 386,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'isdcode' => 44,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 200,'code' => 'SB','name' => "Solomon Islands",'isdcode' => 677,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 201,'code' => 'SO','name' => "Somalia",'isdcode' => 252,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 202,'code' => 'ZA','name' => "South Africa",'isdcode' => 27,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 203,'code' => 'GS','name' => "South Georgia",'isdcode' => 500,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 204,'code' => 'SS','name' => "South Sudan",'isdcode' => 211,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 205,'code' => 'ES','name' => "Spain",'isdcode' => 34,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 206,'code' => 'LK','name' => "Sri Lanka",'isdcode' => 94,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 207,'code' => 'SD','name' => "Sudan",'isdcode' => 249,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 208,'code' => 'SR','name' => "Suriname",'isdcode' => 597,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'isdcode' => 47,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 210,'code' => 'SZ','name' => "Swaziland",'isdcode' => 268,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 211,'code' => 'SE','name' => "Sweden",'isdcode' => 46,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 212,'code' => 'CH','name' => "Switzerland",'isdcode' => 41,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 213,'code' => 'SY','name' => "Syria",'isdcode' => 963,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 214,'code' => 'TW','name' => "Taiwan",'isdcode' => 886,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 215,'code' => 'TJ','name' => "Tajikistan",'isdcode' => 992,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 216,'code' => 'TZ','name' => "Tanzania",'isdcode' => 255,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 217,'code' => 'TH','name' => "Thailand",'isdcode' => 66,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 218,'code' => 'TG','name' => "Togo",'isdcode' => 228,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 219,'code' => 'TK','name' => "Tokelau",'isdcode' => 690,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 220,'code' => 'TO','name' => "Tonga",'isdcode' => 676,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'isdcode' => 1868,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 222,'code' => 'TN','name' => "Tunisia",'isdcode' => 216,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 223,'code' => 'TR','name' => "Turkey",'isdcode' => 90,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 224,'code' => 'TM','name' => "Turkmenistan",'isdcode' => 993,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'isdcode' => 1649,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 226,'code' => 'TV','name' => "Tuvalu",'isdcode' => 688,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 227,'code' => 'UG','name' => "Uganda",'isdcode' => 256,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 228,'code' => 'UA','name' => "Ukraine",'isdcode' => 380,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 229,'code' => 'AE','name' => "United Arab Emirates",'isdcode' => 971,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 230,'code' => 'GB','name' => "United Kingdom",'isdcode' => 44,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 231,'code' => 'US','name' => "United States",'isdcode' => 1,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'isdcode' => 246,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 233,'code' => 'UY','name' => "Uruguay",'isdcode' => 598,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 234,'code' => 'UZ','name' => "Uzbekistan",'isdcode' => 998,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 235,'code' => 'VU','name' => "Vanuatu",'isdcode' => 678,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'isdcode' => 39,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 237,'code' => 'VE','name' => "Venezuela",'isdcode' => 58,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 238,'code' => 'VN','name' => "Vietnam",'isdcode' => 84,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'isdcode' => 1284,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'isdcode' => 1340,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'isdcode' => 681,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 242,'code' => 'EH','name' => "Western Sahara",'isdcode' => 212,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 243,'code' => 'YE','name' => "Yemen",'isdcode' => 967,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 244,'code' => 'YU','name' => "Yugoslavia",'isdcode' => 38,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 245,'code' => 'ZM','name' => "Zambia",'isdcode' => 260,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
    		array('id' => 246,'code' => 'ZW','name' => "Zimbabwe",'isdcode' => 263,'status' => 1,'created_at' => date('Y-m-d H:i:s')),
		);

        foreach($countries as $value){
            Country::updateOrCreate(['id' => $value['id']], [
                'name' => $value['name'],
                'name_ch' => $value['name'],
                'code' => $value['code']
            ]);
        }

    }
}
